### ISSUE TITLE
Add the service to place wishlists items into the wishlist collection

### ISSUE THREAD

**Issue by sqz0914** [wishlists/wishlists#11]
**As a** User
**I need** the ability to place wishlists items into the wishlist collection
**So that** I can keep track of the items that I wish I had the money to purchase

**Assumptions:** 
* A call to ``` GET /wishlists ``` should show all the existing wishlists
* The wishlist ID should be passed in by the user
* A list of items ID should be provided by the user
* A call to ``` POST /wishlists/{id}/items ``` should add these wishlist items into the designated wishlist collection of products

**Acceptance Criteria:**

When I call ``` GET /wishlists ```
I should see a list of all wishlists as a JSON string
Then I call ``` POST /wishlists/{id}/items ```
I should see a message indicating adding the items to the wishlist successfully, and also see the content of that wishlist after adding items

**Comment by abhinavGupta16** [comment]
Updating the story to change PUT to POST
