### ISSUE TITLE
Add the service to QUERY a wishlist

### ISSUE THREAD

**Issue by xiafanzeng** [wishlists/wishlists#14]
**As a** User
**I need** the ability to query wishlists  
**So that** I can search and locate wishlist according to my needs  

**Assumptions:** 
* The value of a query parameter should be pass in by the user
* Query parameters are separated from the URL path by a question mark {?} and multiple parameters are delimited by an ampersand {&}.
* Query parameters can be used to pass in a filter to be applied to the results that should be returned by a particular operation
* A call to ```GET /wishlists``` should list all wishlists

**Acceptance Criteria:**
When I call ```GET /wishlists?name="John_wishlist"``` 
Then I should see the wishlist with name "John_wishlist" as a JSON string

**Comment by xiafanzeng** [comment]
Merged to story "Add Wishlists LIST and QUERY API"

**Comment by abhinavGupta16** [comment]
Moving it to Q/A as the PR is still not approved and merged. Also, I believe this story should be assigned to @sqz0914 since the PR #32  belongs to @sqz0914

**Comment by xiafanzeng** [comment]
Changed the Assignee
