### ISSUE TITLE
Add error handlers

### ISSUE THREAD

**Issue by yf1357** [wishlists/wishlists#23]
**As a** developer  
**I need** the unified error handlers
**So that** we can override the default error handlers and ensure that only JSON message returned.

**Assumptions:** 
* Vagrant file and Skeleton Flask is set up

**Acceptance Criteria:**
```
Given - I have a created error handler
When I put a wrong request on web page
Then the error message will be returned in JSON format
```

**Comment by abhinavGupta16** [comment]
We need to prioritize this issue so the rest of the REST APIs can then handle validation.

**Comment by Jesse1204** [comment]
> We need to prioritize this issue so the rest of the REST APIs can then handle validation.

Gotcha
