### ISSUE TITLE
Add the service to UPDATE an existing item in a wishlist

### ISSUE THREAD

**Issue by abhinavGupta16** [wishlists/wishlists#38]
**As a** User
**I need** the ability to update the item details in my wishlist
**So that** so that I can easily edit my item list in my wishlist

**Assumptions:** 
* A call to ``` GET /wishlists/{id}/items ``` should show all the existing items in the wishlists
* The wishlist ID and the item ID should be passed in by the user
* A call to ``` GET /wishlists/{id}/item/{id} ``` should show the content of the designated item in the wishlist
* A call to ``` PUT /wishlists/{id}/item/{id} ``` should update the content of the designated item in the wishlist in the database

**Acceptance Criteria:**

When I call ``` GET /wishlists/{id}/items ```
I should see a list of all items in the wishlists as a JSON string
Then I call ``` GET /wishlists/{id}/items/{id} ```
I should see the content of the item in the wishlist that I want to review
Then I call ``` PUT /wishlists/{id}/items/{id} ```
I should see a message indicating updating the item in the wishlist successfully, and also see the content of the updated item

**Code Reference**
You can refer to https://github.com/nyu-devops/sample-accounts/blob/master/service/service.py#L256 for a sample implementation.

**Comment by yf1357** [comment]
There is no need for update method. "GET /wishlists/{id}/items" is included in another story.

**Comment by abhinavGupta16** [comment]
Removed the update item API and test case after discussion with the team.
