### ISSUE TITLE
Add the service to LIST all items in my Wishlist

### ISSUE THREAD

**Issue by abhinavGupta16** [wishlists/wishlists#39]
**As a** User
**I need** the ability to list all items in my wishlist
**So that** I can see all the existing items in my wishlist and may perform further actions on the items of my wishlists

**Assumptions:** 
User will pass the wishlist ID
* A call to ``` GET /wishlist/{id}/items ``` should list all wishlists

**Acceptance Criteria:**

When I call ``` GET /wishlists/{id}/items ```
I should see a list of all items in my wishlist as a JSON string

**Code Reference**
You can refer to https://github.com/nyu-devops/sample-accounts/blob/master/service/service.py#L211 for a sample implementation.

**Comment by yf1357** [comment]
I think GET /wishlist/{id} can return all the items in the list.

**Comment by abhinavGupta16** [comment]
I think the point is, I want only items, not the wishlist. Prof has it in sample-accounts as well.
