### ISSUE TITLE
Set up the DevOps Continuous Delivery Pipeline in IBM Cloud

### ISSUE THREAD

**Issue by sqz0914** [wishlists/wishlists#59]
**As a** Developer 
**I need** the DevOps continuous delivery pipeline 
**So that** when I commit a new service to the master branch of the wishlists GitHub repo, it will be deployed to the IBM Cloud automatically 

**Assumptions:** 
* The pipeline has 4 stages: Build, Dev, Test, Prod
* Each stage could run successfully

**Acceptance Criteria:**

Given a new service is committed to the master branch of the wishlists repo
When the associated pull request is approved
Then the pipeline will start to operate and deploy the new service to the IBM Cloud

**Comment by xiafanzeng** [comment]
Minor Stories exist
