### ISSUE TITLE
Add Swagger data models

### ISSUE THREAD

**Issue by Jesse1204** [wishlists/wishlists#72]
**As a** developer  
**I need** to add Swagger data models
**So that** we are able to document API payloads

**Assumptions:** 
* Refactoring with Flask-RESTPlus is done

**Acceptance Criteria:**
```
Given I look into the document 
When I try to understand the API payloads
Then I'm able to find the swagger data models which help me to understand
```

**Comment by abhinavGupta16** [comment]
Duplicate Issue. Not required.
